### ISSUE TITLE
Issue running bot

### ISSUE THREAD

**Issue by Nuklez16** [pdemian/Discord-Stock-Bot#3]
Hi there,

Having issues running the bot I have the .env in the directory with the following
DISCORD_TOKEN=BOTTOKENISHERE

![image](https://user-images.githubusercontent.com/18061996/149848450-1689515c-d4fb-4b9e-9feb-89c62925be62.png)

**Comment by pdemian** [comment]
The offending line of code would probably be line 30 as that's actually grabbing the env variable. It's `const token = process.env['DISCORD_TOKEN'];` Then line 247 actually uses it. `client.login(token);` 

I can't see any particular reason why that wouldn't work if it's defined in your environment. You could try debugging dotenv with the steps listed here: https://stackoverflow.com/questions/26973484/how-do-i-setup-the-dotenv-file-in-node-js or https://www.mariokandut.com/how-to-set-up-and-test-a-dot-env-file-in-node-js/ however you're using .env.

If you're not too bothered by it, you can also just hardcode the bot token there.

The alternative is that your bot token is invalid. Can't really help you with that if that's the case. Your best bet would be to contact Discord themselves.

**Comment by Nuklez16** [comment]
adjusted code to suit as below 

`const token = "YOURBOTCODE HERE";`

**Comment by Nuklez16** [comment]
Would be good to see charts implemented at all?

**Comment by pdemian** [comment]
Hi,

Not at this time, I don't have plans for it.

Feel free to submit a change request if you can do it.
